app = "chatbot-backend-badr"  # Unique name
primary_region = "iad"  # Free tier region (Virginia, US)

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  PYTHONUNBUFFERED = "1"
  DEBUG = "true"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0  # Free tier spins down when idle

[checks]
  [checks.http]
    port = 8000
    type = "http"
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"  # Changed to GET
    path = "/chat/health/"  # New endpoint
